/**
 * Email-wide constants. Pure data, safe to import from anywhere (no secrets,
 * no Resend). URLs read NEXT_PUBLIC_APP_URL when present so links + the hosted
 * logo PNG resolve to the live origin; otherwise they fall back to production.
 */

export const PRODUCT_NAME = "RecompIQ";

/** Canonical origin for links and the hosted logo. */
export const APP_URL = (
  process.env.NEXT_PUBLIC_APP_URL ?? "https://recompiq.vercel.app"
).replace(/\/$/, "");

/** Hosted PNG logo assets (generated by scripts/build-logo-assets.mjs). */
export const LOGO_MARK_URL = `${APP_URL}/email/logo-mark.png`;
export const LOGO_MARK_2X_URL = `${APP_URL}/email/logo-mark@2x.png`;

/** Outbound identity. */
export const FROM_NAME = PRODUCT_NAME;
export const FROM_EMAIL =
  process.env.EMAIL_FROM ?? "RecompIQ <noreply@recompiq.com>";
export const REPLY_TO = process.env.EMAIL_REPLY_TO ?? "support@recompiq.com";

/**
 * Physical mailing address — REQUIRED in commercial email footers (CAN-SPAM /
 * CASL). Placeholder until the operating entity + address are finalized.
 */
export const MAILING_ADDRESS =
  process.env.EMAIL_MAILING_ADDRESS ??
  "RecompIQ · [Mailing Address] · [City, State ZIP]";

/** Where the unsubscribe link points until a notifications backend exists. */
export const DEFAULT_UNSUBSCRIBE_URL = `${APP_URL}/settings/notifications`;

/** Verbatim compliance string — fixed, never paraphrased per the brand voice. */
export const DISCLAIMER_LEAD =
  "For educational and research purposes only. Not medical advice.";
export const DISCLAIMER_BODY =
  "RecompIQ does not prescribe, sell, supply, or recommend any compound. Always consult a licensed clinician.";

/** Common links surfaced in footers. */
export const LINKS = {
  legal: `${APP_URL}/legal`,
  disclaimer: `${APP_URL}/legal/medical-disclaimer`,
  research: `${APP_URL}/legal/research-use`,
  privacy: `${APP_URL}/legal/privacy`,
  terms: `${APP_URL}/legal/terms`,
  dashboard: `${APP_URL}/dashboard`,
  settings: `${APP_URL}/settings`,
} as const;
